In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [2]:
# CountVectorizer
cv = CountVectorizer()

In [3]:
x_traincv = cv.fit_transform(["Book a flight from bali to mumbai on 3rd of March","Booking flight is very Easy now  a day", "book a flight in economy class "])

In [4]:
x_traincv.toarray()

array([[1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [5]:
cv.get_feature_names()

['3rd',
 'bali',
 'book',
 'booking',
 'class',
 'day',
 'easy',
 'economy',
 'flight',
 'from',
 'in',
 'is',
 'march',
 'mumbai',
 'now',
 'of',
 'on',
 'to',
 'very']

In [45]:
dataset = pd.read_excel('classifier.xlsx',column = ['Status','Message'])

In [46]:
dataset.loc[dataset["Status"] == 1, "Status",] = 1
dataset.loc[dataset["Status"] == 2, "Status",] = 0

In [47]:
X = dataset["Message"].values
y = dataset["Status"].values

In [48]:
dataset

Status                                            Message
0        1      Book me a flight from  Indore on 2nd october 
1        0                                     Time is money 
2        1  Book me a flight from mumbai to indore and als...
3        0  Children play with each other and learn new th...
4        1  Book me a flight from sydney to delhi for  2 p...
5        0  This place has really good views but it is out...
6        1  Book me a flight from  Mumbai on 4th july with...
7        0  My budget is low so we need to compromise on s...
8        1  Book me a flight with checkin on 2nd april in ...
9        1  Their flight is landed two hr. Late so they mi...
10       0        No one else should me blamed for my mistake
11       1  Booking hotels and flight is very easy now a d...
12       0  India is a very beautiful country and most thi...
13       1  Book me a flight  for 2 adults and two childre...
14       0        I love this area! Its so close to the city.
15       1              Book me a flight from mumbai to  goa 
16       0  Book me hotel Grand Hyatt in Berlin for 5 days...
17       1  PM modi flight landed in  Usa at night 3 ‘o cl...
18       1  book me a first class flight from indore to de...
19       0  Book me a luxury hotel in bali with 24 hour ro...
20       1  book me a cheapest flight fom mumbai to chenna...
21       0  Book me a budget friendly hotel in berlin near...
22       1  book me a standard room with double beds in a ...
23       0  book me a standard double room in lonavala wit...
24       1  book a flight using genie talk app so we can g...
25       1         book me a direct flight from Agra to Delhi
26       1  book me a red eye flight on 4th April from Ber...
27       1  book me a flight from Frankfurt to London  at ...
28       1  book me a flight from Frankfurt to London at 3...

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 5)

In [50]:
cv = CountVectorizer()
X_traincv = cv.fit_transform(X_train)
X_testcv = cv.transform(X_test)
y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [57]:
X_testcv= cv.transform(["Book me a cab from A to B"])
X_testcv.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:

naive_bayes = MultinomialNB()
naive_bayes.fit(X_traincv, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [59]:
y_test_pred = naive_bayes.predict(X_testcv)

In [60]:
# Training accuracy
naive_bayes.score(X_traincv, y_train)

1.0

In [61]:
# Testing accuracy
# naive_bayes.score(X_testcv, y_test)

In [62]:
naive_bayes.predict(X_testcv)

array([1])